//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.02 at 06:56:28 AM KST 
//


package com.sds.metac.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="programming" type="{http://www.samsung.com/sds/ssa8-2/PostProcessorConfiguration}languageType"/>
 *         &lt;element name="compileConfiguration" type="{http://www.samsung.com/sds/ssa8-2/PostProcessorConfiguration}compileConfiguration"/>
 *         &lt;element name="createJarConfiguration" type="{http://www.samsung.com/sds/ssa8-2/PostProcessorConfiguration}createJarConfiguration"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "postProcessorConfiguration")
public class PostProcessorConfiguration {

    @XmlElement(required = true)
    protected LanguageType programming;
    @XmlElement(required = true)
    protected CompileConfiguration compileConfiguration;
    @XmlElement(required = true)
    protected CreateJarConfiguration createJarConfiguration;

    /**
     * Gets the value of the programming property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageType }
     *     
     */
    public LanguageType getProgramming() {
        return programming;
    }

    /**
     * Sets the value of the programming property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageType }
     *     
     */
    public void setProgramming(LanguageType value) {
        this.programming = value;
    }

    /**
     * Gets the value of the compileConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link CompileConfiguration }
     *     
     */
    public CompileConfiguration getCompileConfiguration() {
        return compileConfiguration;
    }

    /**
     * Sets the value of the compileConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompileConfiguration }
     *     
     */
    public void setCompileConfiguration(CompileConfiguration value) {
        this.compileConfiguration = value;
    }

    /**
     * Gets the value of the createJarConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link CreateJarConfiguration }
     *     
     */
    public CreateJarConfiguration getCreateJarConfiguration() {
        return createJarConfiguration;
    }

    /**
     * Sets the value of the createJarConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateJarConfiguration }
     *     
     */
    public void setCreateJarConfiguration(CreateJarConfiguration value) {
        this.createJarConfiguration = value;
    }

}
