//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.10 at 06:09:36 PM KST 
//


package com.sds.metac.schema.information;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.samsung.com/sds/ssa8-2/information}ClassInformationType"/>
 *         &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uiClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassInformation", propOrder = {
    "name",
    "type",
    "className",
    "uiClassName",
    "classFilePath"
})
public class ClassInformation {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected ClassInformationType type;
    @XmlElement(required = true)
    protected String className;
    @XmlElement(required = true)
    protected String uiClassName;
    @XmlElement(required = true)
    protected String classFilePath;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ClassInformationType }
     *     
     */
    public ClassInformationType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassInformationType }
     *     
     */
    public void setType(ClassInformationType value) {
        this.type = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the uiClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiClassName() {
        return uiClassName;
    }

    /**
     * Sets the value of the uiClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiClassName(String value) {
        this.uiClassName = value;
    }

    /**
     * Gets the value of the classFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassFilePath() {
        return classFilePath;
    }

    /**
     * Sets the value of the classFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassFilePath(String value) {
        this.classFilePath = value;
    }

}
