//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.10 at 06:09:36 PM KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.samsung.com/sds/ssa8-2/information", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sds.metac.schema.information;
