//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.22 at 01:10:23 AM KST 
//


package com.sds.metac.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for outputWriterInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="outputWriterInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="metaFomula" type="{http://www.samsung.com/sds/ssa8-2/information}MetaFomula"/>
 *         &lt;element name="singleCharYn" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="variableSyntax" type="{http://www.samsung.com/sds/ssa8-2/information}VariableSyntax"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "outputWriterInformation", propOrder = {
    "metaFomula",
    "singleCharYn",
    "variableSyntax"
})
public class OutputWriterInformation {

    @XmlElement(required = true)
    protected MetaFomula metaFomula;
    protected boolean singleCharYn;
    @XmlElement(required = true)
    protected VariableSyntax variableSyntax;

    /**
     * Gets the value of the metaFomula property.
     * 
     * @return
     *     possible object is
     *     {@link MetaFomula }
     *     
     */
    public MetaFomula getMetaFomula() {
        return metaFomula;
    }

    /**
     * Sets the value of the metaFomula property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaFomula }
     *     
     */
    public void setMetaFomula(MetaFomula value) {
        this.metaFomula = value;
    }

    /**
     * Gets the value of the singleCharYn property.
     * 
     */
    public boolean isSingleCharYn() {
        return singleCharYn;
    }

    /**
     * Sets the value of the singleCharYn property.
     * 
     */
    public void setSingleCharYn(boolean value) {
        this.singleCharYn = value;
    }

    /**
     * Gets the value of the variableSyntax property.
     * 
     * @return
     *     possible object is
     *     {@link VariableSyntax }
     *     
     */
    public VariableSyntax getVariableSyntax() {
        return variableSyntax;
    }

    /**
     * Sets the value of the variableSyntax property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableSyntax }
     *     
     */
    public void setVariableSyntax(VariableSyntax value) {
        this.variableSyntax = value;
    }

}
