//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.11 at 12:48:24 AM KST 
//


package com.sds.metac.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="metaFomula" type="{http://www.samsung.com/sds/ssa8-2/outputWriterConfig}MetaFomula"/>
 *         &lt;element name="variableSyntax" type="{http://www.samsung.com/sds/ssa8-2/outputWriterConfig}VariableSyntax"/>
 *         &lt;element name="minCharSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tempFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metaFomula",
    "variableSyntax",
    "minCharSize",
    "tempFilePath"
})
@XmlRootElement(name = "outputWriterConfig")
public class OutputWriterConfig {

    @XmlElement(required = true)
    protected MetaFomula metaFomula;
    @XmlElement(required = true)
    protected VariableSyntax variableSyntax;
    protected int minCharSize;
    @XmlElement(required = true)
    protected String tempFilePath;

    /**
     * Gets the value of the metaFomula property.
     * 
     * @return
     *     possible object is
     *     {@link MetaFomula }
     *     
     */
    public MetaFomula getMetaFomula() {
        return metaFomula;
    }

    /**
     * Sets the value of the metaFomula property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaFomula }
     *     
     */
    public void setMetaFomula(MetaFomula value) {
        this.metaFomula = value;
    }

    /**
     * Gets the value of the variableSyntax property.
     * 
     * @return
     *     possible object is
     *     {@link VariableSyntax }
     *     
     */
    public VariableSyntax getVariableSyntax() {
        return variableSyntax;
    }

    /**
     * Sets the value of the variableSyntax property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableSyntax }
     *     
     */
    public void setVariableSyntax(VariableSyntax value) {
        this.variableSyntax = value;
    }

    /**
     * Gets the value of the minCharSize property.
     * 
     */
    public int getMinCharSize() {
        return minCharSize;
    }

    /**
     * Sets the value of the minCharSize property.
     * 
     */
    public void setMinCharSize(int value) {
        this.minCharSize = value;
    }

    /**
     * Gets the value of the tempFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTempFilePath() {
        return tempFilePath;
    }

    /**
     * Sets the value of the tempFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTempFilePath(String value) {
        this.tempFilePath = value;
    }

}
