//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.01 at 12:28:09 AM KST 
//


package com.sds.metac.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VariableSyntax.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VariableSyntax">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="camelCase"/>
 *     &lt;enumeration value="underscoreCase"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VariableSyntax")
@XmlEnum
public enum VariableSyntax {

    @XmlEnumValue("camelCase")
    CAMEL_CASE("camelCase"),
    @XmlEnumValue("underscoreCase")
    UNDERSCORE_CASE("underscoreCase");
    private final String value;

    VariableSyntax(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VariableSyntax fromValue(String v) {
        for (VariableSyntax c: VariableSyntax.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
