//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.02 at 06:38:39 AM KST 
//


package com.sds.metac.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for configuration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="inputFilesPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="standardFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="commonCodeFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configuration", propOrder = {

})
public class Configuration {

    @XmlElement(required = true)
    protected String inputFilesPath;
    @XmlElement(required = true)
    protected String standardFileName;
    @XmlElement(required = true)
    protected String commonCodeFileName;

    /**
     * Gets the value of the inputFilesPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputFilesPath() {
        return inputFilesPath;
    }

    /**
     * Sets the value of the inputFilesPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputFilesPath(String value) {
        this.inputFilesPath = value;
    }

    /**
     * Gets the value of the standardFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardFileName() {
        return standardFileName;
    }

    /**
     * Sets the value of the standardFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardFileName(String value) {
        this.standardFileName = value;
    }

    /**
     * Gets the value of the commonCodeFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonCodeFileName() {
        return commonCodeFileName;
    }

    /**
     * Sets the value of the commonCodeFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonCodeFileName(String value) {
        this.commonCodeFileName = value;
    }

}
